import type { Metadata } from "next";

import ConnectedHeader from "@/components/Header/ConnectedHeader";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ConnectedHeader />
      {children}
    </>
  );
}
